# Generated by Django 6.0.2 on 2026-02-27 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('metric', 'Metric'), ('list', 'List')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart')], max_length=20, null=True)),
                ('report_type', models.CharField(choices=[('patient_census', 'Patient Census'), ('admission_discharge', 'Admission & Discharge Summary'), ('diagnosis_frequency', 'Diagnosis Frequency'), ('prescription_analysis', 'Prescription Analysis'), ('lab_utilization', 'Lab Utilization'), ('imaging_utilization', 'Imaging Utilization'), ('patient_demographics', 'Patient Demographics'), ('length_of_stay', 'Length of Stay Analysis'), ('readmission_rate', 'Readmission Rate'), ('mortality_rate', 'Mortality Rate'), ('physician_workload', 'Physician Workload'), ('department_performance', 'Department Performance'), ('custom', 'Custom Report')], max_length=50)),
                ('data_config', models.JSONField(default=dict, help_text='JSON configuration for data query')),
                ('width', models.IntegerField(default=6, help_text='Bootstrap column width (1-12)')),
                ('height', models.IntegerField(default=300, help_text='Height in pixels')),
                ('refresh_interval', models.IntegerField(default=0, help_text='Refresh interval in minutes (0 = no refresh)')),
                ('row_order', models.IntegerField(default=0)),
                ('column_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['row_order', 'column_order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('patient_census', 'Patient Census'), ('admission_discharge', 'Admission & Discharge Summary'), ('diagnosis_frequency', 'Diagnosis Frequency'), ('prescription_analysis', 'Prescription Analysis'), ('lab_utilization', 'Lab Utilization'), ('imaging_utilization', 'Imaging Utilization'), ('patient_demographics', 'Patient Demographics'), ('length_of_stay', 'Length of Stay Analysis'), ('readmission_rate', 'Readmission Rate'), ('mortality_rate', 'Mortality Rate'), ('physician_workload', 'Physician Workload'), ('department_performance', 'Department Performance'), ('custom', 'Custom Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('clinical', 'Clinical Reports'), ('administrative', 'Administrative Reports'), ('financial', 'Financial Reports'), ('operational', 'Operational Reports'), ('statistical', 'Statistical Reports')], max_length=50)),
                ('report_type', models.CharField(choices=[('patient_census', 'Patient Census'), ('admission_discharge', 'Admission & Discharge Summary'), ('diagnosis_frequency', 'Diagnosis Frequency'), ('prescription_analysis', 'Prescription Analysis'), ('lab_utilization', 'Lab Utilization'), ('imaging_utilization', 'Imaging Utilization'), ('patient_demographics', 'Patient Demographics'), ('length_of_stay', 'Length of Stay Analysis'), ('readmission_rate', 'Readmission Rate'), ('mortality_rate', 'Mortality Rate'), ('physician_workload', 'Physician Workload'), ('department_performance', 'Department Performance'), ('custom', 'Custom Report')], max_length=50)),
                ('template_config', models.JSONField(default=dict, help_text='JSON configuration for report template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('patient_census', 'Patient Census'), ('admission_discharge', 'Admission & Discharge Summary'), ('diagnosis_frequency', 'Diagnosis Frequency'), ('prescription_analysis', 'Prescription Analysis'), ('lab_utilization', 'Lab Utilization'), ('imaging_utilization', 'Imaging Utilization'), ('patient_demographics', 'Patient Demographics'), ('length_of_stay', 'Length of Stay Analysis'), ('readmission_rate', 'Readmission Rate'), ('mortality_rate', 'Mortality Rate'), ('physician_workload', 'Physician Workload'), ('department_performance', 'Department Performance'), ('custom', 'Custom Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(default='08:00')),
                ('parameters', models.JSONField(default=dict)),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
