# Generated by Django 6.0.2 on 2026-02-26 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammogram', 'Mammogram'), ('pet', 'PET Scan')], max_length=20)),
                ('body_part', models.CharField(max_length=100)),
                ('clinical_history', models.TextField()),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='imaging/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='imaging_reports/')),
                ('imaging_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='records.imagingorder')),
                ('radiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('collected_date', models.DateTimeField(blank=True, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=100)),
                ('clinical_notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=200)),
                ('reference_range', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('performed_date', models.DateTimeField(auto_now_add=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='records.laborder')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=20, unique=True)),
                ('record_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow Up'), ('emergency', 'Emergency'), ('routine_check', 'Routine Check'), ('pre_surgery', 'Pre-Surgery'), ('post_surgery', 'Post-Surgery')], max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('review_of_systems', models.TextField(blank=True)),
                ('physical_exam', models.TextField(blank=True)),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='records.medicalrecord'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic'), ('rule_out', 'Rule Out')], default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('nursing', 'Nursing Note'), ('consult', 'Consultation Note'), ('discharge', 'Discharge Summary'), ('transfer', 'Transfer Note')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(choices=[('mg', 'mg'), ('mcg', 'mcg'), ('g', 'g'), ('ml', 'ml'), ('tablet', 'tablet(s)'), ('capsule', 'capsule(s)'), ('puff', 'puff(s)'), ('drop', 'drop(s)')], max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('bid', 'Twice Daily'), ('tid', 'Three Times Daily'), ('qid', 'Four Times Daily'), ('q4h', 'Every 4 hours'), ('q6h', 'Every 6 hours'), ('q8h', 'Every 8 hours'), ('q12h', 'Every 12 hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('prn', 'As Needed')], max_length=20)),
                ('route', models.CharField(max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('refills', models.IntegerField(default=0)),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_code', models.CharField(max_length=20)),
                ('date_performed', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('findings', models.TextField()),
                ('complications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assisted_by', models.ManyToManyField(blank=True, related_name='assisted_procedures', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='records.medicalrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
