# Generated by Django 6.0.2 on 2026-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='test_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
